### ISSUE TITLE
Amazingly good! Could you please share the weekly template?

### ISSUE THREAD

**Issue by h-jia** [jmeischner/alfred-bear#1]
Hi! Thanks for making these amazing templates!

Could you please share the weekly review template? I have inspired a lot from your daily bear template and hopefully can learn from the weekly version as well.

Regards, 
Eddy

**Comment by jmeischner** [comment]
Hej Eddy,

I'm happy that these things are helpful :-)

I have a weekly review template to get everything up-to-date once a week, which I'm happy to share. What I don't have is a weekly log template (as used for bullet journaling)

Here is my weekly review template:
<img width="832" alt="weekly" src="https://user-images.githubusercontent.com/7792451/96775549-f85ab780-13e7-11eb-932c-a025f3776784.png">

```md
# Weekly Review
- - - -
#1 - projects/weekly#
- - - -

::Empty out my head::
- [ ] Is there anything which comes to mind spontaneously which needs to get done?

::Take a look into the calendar?::
- [ ] Which appointments did I have last week? Are there impulses or todos which come from them?
- [ ] Which appointments will I have in the next week and is there anything which needs to be done for them?

::Clean the inboxes::
- [ ] Email
- [ ] *Things* - [inbox](things:///show?id=inbox)
- [ ] *Bear* - Is everything [tagged](bear://x-callback-url/untagged)

::Review Things::
- [ ] Is there anything in the: [wait](things:///show?query=warten)  status - Is this already done or are there any news related to them?
- [ ] Review [Projects overview](things:///show?id=all-projects) check for up-to-dateness - are there any *next steps*?
- [ ] Which *[next steps](things:///show?query=n%C3%A4chste%20schritte)]* did I plan - is something already done or deferred?
- [ ] Which things did I [plan](things:///show?id=upcoming)  for the next week - are some days too cluttered?
- [ ] Are there next steps which I can plan for the next days - when do I have open time slots?

::Review Bear::
- [ ] Is the [[Project Overview]] up to date?

::Short Recap::
- [ ] [[Weekly Recap]]
```

Where **Project Overview** is a bear note which holds something like a *table of contents* to my current running project bear notes and **Weekly Recap** is a bear note where I write a few sentences (like a Journal) for every calendar week (as last step of my weekly review)

**Comment by h-jia** [comment]
Thanks for sharing! @jmeischner

I have learnt mega!!! Much much appreciate!
